# -*- mode: ruby -*-
# vi: set ft=ruby tabstop=2

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "70"]
    v.customize ["modifyvm", :id, "--memory", "512"]
  end

  # Setup server
  config.vm.provision "webserver", type: "ansible" do |ansible|
    ansible.extra_vars = {
      ansible_ssh_user: 'vagrant',
      deploy_user: 'vagrant',
      docker_group_members: ['vagrant'],
    }

    ansible.playbook = "prepare_server.yml"
  end
end
